version: '3.0'

services:
  mongo:
    image: mongo
    container_name: TerceraPreEntrega
    ports:
      - 27017:27017
    volumes:
      - TerceraPreEntrega:/data/configdb
      - TerceraPreEntrega:/data/db

volumes:
  TerceraPreEntrega: {}