version: '3.0'

services:
  mongo:
    image: mongo
    container_name: TerceraPreEntrega
    ports:
      - 27017:27017
    volumes:
      - TerceraPreEntrega:/data/configdb
      - TerceraPreEntrega:/data/db

  api:
    build: .
    container_name: api_container
    ports:
      - 9000:9000
    depends_on:
      - mongo
    restart: always
    volumes:
      - .:/usr/src/app

volumes:
  TerceraPreEntrega: {}