openapi: 3.0.0
info:
  title: Mailing Documentation
  version: 1.0.0
paths:
  /mailing/email/send:
    post:
      summary: Send an email
      tags:
        - Mailing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
      responses:
        '200':
          description: Email sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /mailing/sms/send:
    post:
      summary: Send an SMS
      tags:
        - Mailing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsRequest'
      responses:
        '200':
          description: SMS sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
components:
  schemas:
    EmailRequest:
      type: object
      properties:
        email:
          type: string
          description: The email address of the recipient.
      required:
        - email
      example:
        email: "recipient@example.com"
    SmsRequest:
      type: object
      properties:
        name:
          type: string
          description: The recipient's name.
        phone:
          type: string
          description: The recipient's phone number.
      required:
        - name
        - phone
      example:
        name: "John Doe"
        phone: "+1234567890"
    MessageResponse:
      type: object
      properties:
        ok:
          type: boolean
          description: Indicates whether the operation was successful.
        message:
          type: string
          description: A message describing the result of the operation.
      example:
        ok: true
        message: "Email sent to recipient@example.com"
